import * as SQLite from 'expo-sqlite';
import type { Exercise, WorkoutTemplate, Program } from '@/types';

// ─── Exercises ────────────────────────────────────────────────────────────────

const EXERCISES: Exercise[] = [
  // MUSCULATION - PECTORAUX
  {
    id: 'bench_press',
    name: 'Développé Couché',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    primaryMuscle: 'chest',
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    description: 'L\'exercice roi pour développer les pectoraux. Mouvement de poussée horizontal à la barre.',
    instructions: [
      'Allonge-toi sur le banc, les yeux sous la barre.',
      'Prends la barre en prise pronation, mains légèrement plus larges que les épaules.',
      'Décolle la barre et amène-la à hauteur de poitrine.',
      'Descends la barre jusqu\'à toucher légèrement le bas des pectoraux.',
      'Pousse explosément vers le haut en expirant.',
    ],
    coachTips: [
      'Garde les omoplates serrées et les pieds bien à plat sur le sol.',
      'La barre doit toucher le bas des pectoraux, pas la gorge.',
      'Maintiens une légère cambrure naturelle du dos.',
    ],
    commonMistakes: [
      'Lever les fesses du banc',
      'Laisser les coudes s\'écarter trop loin du corps',
      'Ne pas descendre assez bas',
    ],
    defaultSets: 4,
    defaultReps: 8,
    defaultRest: 120,
  },
  {
    id: 'incline_bench_press',
    name: 'Développé Incliné',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    primaryMuscle: 'chest',
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    description: 'Variante inclinée pour cibler le faisceau supérieur des pectoraux.',
    instructions: [
      'Incline le banc à 30-45 degrés.',
      'Prends la barre avec une prise légèrement plus large que les épaules.',
      'Descends la barre vers le haut des pectoraux.',
      'Pousse vers le haut et légèrement vers l\'arrière.',
    ],
    coachTips: [
      'Un angle de 30° est plus efficace qu\'un angle de 45°.',
      'Évite de trop incliner pour ne pas trop solliciter les épaules.',
    ],
    commonMistakes: ['Incliner le banc trop haut', 'Perdre la tension en haut du mouvement'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 90,
  },
  {
    id: 'dumbbell_flyes',
    name: 'Écarté Haltères',
    category: 'strength',
    muscleGroups: ['chest'],
    primaryMuscle: 'chest',
    equipment: ['dumbbells', 'bench'],
    difficulty: 'beginner',
    description: 'Exercice d\'isolation pour étirer et contracter les pectoraux.',
    instructions: [
      'Allonge-toi sur le banc avec un haltère dans chaque main.',
      'Étends les bras au-dessus de la poitrine, légèrement fléchis.',
      'Écarte les bras lentement en arc de cercle jusqu\'à sentir l\'étirement.',
      'Reviens à la position de départ en contractant les pectoraux.',
    ],
    coachTips: ['Imagine que tu embrasses un arbre pour la trajectoire.', 'Garde les coudes légèrement fléchis tout au long du mouvement.'],
    commonMistakes: ['Plier trop les coudes (ça devient une presse)', 'Descendre trop bas et stresser les épaules'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'push_up',
    name: 'Pompes',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps', 'abs'],
    primaryMuscle: 'chest',
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    description: 'L\'exercice de base au poids du corps pour les pectoraux et le haut du corps.',
    instructions: [
      'Mets-toi en position de planche, mains légèrement plus larges que les épaules.',
      'Corps bien aligné des talons aux épaules.',
      'Descends en pliant les coudes jusqu\'à ce que la poitrine touche presque le sol.',
      'Remonte en tendant les bras.',
    ],
    coachTips: ['Contracte les abdos tout au long du mouvement.', 'Regarde le sol légèrement devant toi.'],
    commonMistakes: ['Laisser les hanches s\'affaisser', 'Poser les genoux', 'Tête en avant'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'cable_crossover',
    name: 'Croisé Poulie',
    category: 'strength',
    muscleGroups: ['chest'],
    primaryMuscle: 'chest',
    equipment: ['cable'],
    difficulty: 'intermediate',
    description: 'Exercice d\'isolation à la poulie pour finir les pectoraux avec une tension constante.',
    instructions: [
      'Place-toi au centre entre deux poulies hautes.',
      'Saisis une poignée dans chaque main, bras écartés.',
      'Penche légèrement le buste en avant.',
      'Ramène les mains devant toi en contractant les pectoraux.',
    ],
    coachTips: ['Les mains peuvent se croiser en bas pour maximiser la contraction.'],
    commonMistakes: ['Se redresser trop durant le mouvement', 'Utiliser trop de poids et perdre le contrôle'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  // DOS
  {
    id: 'pull_up',
    name: 'Tractions',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    primaryMuscle: 'back',
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    description: 'L\'exercice roi pour développer le dos. Prise supination ou pronation.',
    instructions: [
      'Suspends-toi à la barre, mains en pronation, légèrement plus larges que les épaules.',
      'À partir d\'un blocage complet, tire-toi vers le haut.',
      'Monte jusqu\'à ce que le menton dépasse la barre.',
      'Redescends lentement.',
    ],
    coachTips: [
      'Démarre en protractant les omoplates puis engage le dos.',
      'Évite de te balancer pour prendre de l\'élan.',
    ],
    commonMistakes: ['Utiliser l\'élan', 'Ne pas descendre complètement', 'Creuser excessivement le dos'],
    defaultSets: 4,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'barbell_row',
    name: 'Rowing Barre',
    category: 'strength',
    muscleGroups: ['back', 'biceps', 'forearms'],
    primaryMuscle: 'back',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    description: 'Mouvement de tirage horizontal pour l\'épaisseur du dos.',
    instructions: [
      'Penche-toi à environ 45°, dos droit, barre en main.',
      'Tire la barre vers le nombril en ramenant les coudes le long du corps.',
      'Contracte les omoplates en haut.',
      'Redescends contrôlément.',
    ],
    coachTips: ['Garde le dos droit, ne l\'arrondie jamais.', 'Les coudes restent près du corps pour cibler le dos.'],
    commonMistakes: ['Arrondir le dos', 'Tirer avec les bras plutôt qu\'avec le dos', 'Donner du coup de reins'],
    defaultSets: 4,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'lat_pulldown',
    name: 'Tirage Vertical',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    primaryMuscle: 'back',
    equipment: ['cable', 'machine'],
    difficulty: 'beginner',
    description: 'Alternative aux tractions pour cibler les dorsaux, idéal pour les débutants.',
    instructions: [
      'Assis face à la machine, genoux sous le coussin.',
      'Prends la barre en prise large, pronation.',
      'Tire la barre vers le haut de la poitrine en ramenant les coudes vers le bas.',
      'Reviens lentement à la position initiale.',
    ],
    coachTips: ['Tire avec les coudes, pas avec les mains.', 'Penche légèrement le buste en arrière.'],
    commonMistakes: ['Tirer derrière la nuque', 'Se coucher trop en arrière', 'Balancer le buste'],
    defaultSets: 4,
    defaultReps: 10,
    defaultRest: 75,
  },
  {
    id: 'seated_cable_row',
    name: 'Rowing Poulie Assis',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    primaryMuscle: 'back',
    equipment: ['cable'],
    difficulty: 'beginner',
    description: 'Tirage horizontal à la poulie pour le milieu et l\'épaisseur du dos.',
    instructions: [
      'Assis face à la poulie basse, pieds sur les appuis, genoux légèrement fléchis.',
      'Tire la poignée vers le ventre en serrant les omoplates.',
      'Reviens lentement à la position de départ en étirant le dos.',
    ],
    coachTips: ['Ne te penche pas trop en avant ou en arrière.', 'Contracte le dos pendant 1 seconde en position haute.'],
    commonMistakes: ['Trop se pencher', 'Utiliser les lombaires pour tirer'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 75,
  },
  {
    id: 'deadlift',
    name: 'Soulevé de Terre',
    category: 'strength',
    muscleGroups: ['back', 'glutes', 'hamstrings', 'forearms', 'lower_back'],
    primaryMuscle: 'back',
    equipment: ['barbell'],
    difficulty: 'advanced',
    description: 'L\'exercice polyarticulaire par excellence. Engage l\'ensemble de la chaîne postérieure.',
    instructions: [
      'Barre au sol, pieds dans l\'axe des épaules, sous la barre.',
      'Plie les genoux et saisis la barre, mains en dehors des jambes.',
      'Dos droit, poitrine haute, prends une grande inspiration.',
      'Pousse le sol vers le bas et redresse-toi en gardant la barre contre les jambes.',
      'En haut, tends les hanches et les genoux, omoplates serrées.',
    ],
    coachTips: [
      'La barre doit rester proche des jambes tout au long du mouvement.',
      'Pense à "casser le sol" plutôt qu\'à "soulever la barre".',
      'Ceinture abdominale gainée tout au long.',
    ],
    commonMistakes: ['Arrondir le bas du dos', 'Laisser la barre s\'éloigner du corps', 'Plier les bras'],
    defaultSets: 4,
    defaultReps: 5,
    defaultRest: 180,
  },
  // ÉPAULES
  {
    id: 'overhead_press',
    name: 'Développé Militaire',
    category: 'strength',
    muscleGroups: ['shoulders', 'triceps'],
    primaryMuscle: 'shoulders',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    description: 'Presse verticale debout pour développer les épaules et la force globale du haut du corps.',
    instructions: [
      'Debout ou assis, barre sur la poitrine à hauteur des clavicules.',
      'Prise légèrement plus large que les épaules.',
      'Pousse la barre verticalement au-dessus de la tête.',
      'Rentre la tête quand la barre dépasse le front.',
      'Redescends contrôlément.',
    ],
    coachTips: ['Gaine le ventre pour protéger le dos.', 'Pousse légèrement la tête vers l\'avant en haut du mouvement.'],
    commonMistakes: ['Se cambre excessivement', 'Pousser devant soi au lieu de vers le haut'],
    defaultSets: 4,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'lateral_raise',
    name: 'Élévations Latérales',
    category: 'strength',
    muscleGroups: ['shoulders'],
    primaryMuscle: 'shoulders',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    description: 'Isolation du faisceau latéral des épaules pour les élargir.',
    instructions: [
      'Debout, haltères le long du corps.',
      'Lève les bras latéralement jusqu\'à hauteur des épaules.',
      'Contrôle la descente.',
    ],
    coachTips: ['Le petit doigt légèrement plus haut que le pouce (comme si tu versais de l\'eau).', 'Poids léger, technique parfaite.'],
    commonMistakes: ['Utiliser l\'élan', 'Monter les bras trop haut', 'Pencher le buste'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    category: 'strength',
    muscleGroups: ['shoulders', 'back'],
    primaryMuscle: 'shoulders',
    equipment: ['cable'],
    difficulty: 'beginner',
    description: 'Excellent pour la santé des épaules, ciblant le faisceau postérieur et les rotateurs.',
    instructions: [
      'Poulie haute avec corde, saisie à hauteur de visage.',
      'Tire vers le visage en ouvrant les bras.',
      'Les poignets doivent passer à hauteur des oreilles.',
    ],
    coachTips: ['À intégrer dans chaque séance haut du corps pour la santé des épaules.'],
    commonMistakes: ['Tirer trop bas', 'Ne pas ouvrir les coudes'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  // BRAS
  {
    id: 'barbell_curl',
    name: 'Curl Barre',
    category: 'strength',
    muscleGroups: ['biceps', 'forearms'],
    primaryMuscle: 'biceps',
    equipment: ['barbell'],
    difficulty: 'beginner',
    description: 'Exercice classique d\'isolation pour les biceps.',
    instructions: [
      'Debout, barre en prise supination, bras tendus.',
      'Fléchis les coudes en montant la barre vers les épaules.',
      'Contracte les biceps en haut.',
      'Redescends lentement.',
    ],
    coachTips: ['Les coudes restent fixes contre le corps.', 'Ne balance pas le buste.'],
    commonMistakes: ['Balancer le corps', 'Bouger les coudes', 'Descendre trop vite'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'tricep_dip',
    name: 'Dips aux Barres Parallèles',
    category: 'strength',
    muscleGroups: ['triceps', 'chest', 'shoulders'],
    primaryMuscle: 'triceps',
    equipment: ['bodyweight', 'pull_up_bar'],
    difficulty: 'intermediate',
    description: 'Mouvement au poids du corps très efficace pour triceps et bas des pectoraux.',
    instructions: [
      'Supporte ton poids sur deux barres parallèles, bras tendus.',
      'Descends en pliant les coudes jusqu\'à 90°.',
      'Remonte en te poussant vers le haut.',
    ],
    coachTips: ['Pour cibler les triceps, garde le buste droit. Pour les pectoraux, penche légèrement en avant.'],
    commonMistakes: ['Descendre trop bas et stresser les épaules', 'Pas assez descendre'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 75,
  },
  {
    id: 'skull_crusher',
    name: 'Barre Frontale',
    category: 'strength',
    muscleGroups: ['triceps'],
    primaryMuscle: 'triceps',
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    description: 'Isolation des triceps en position allongée.',
    instructions: [
      'Allongé sur le banc, barre tenue en prise pronation au-dessus de la tête.',
      'Fléchis uniquement les coudes pour descendre la barre vers le front.',
      'Remonte en tendant les bras.',
    ],
    coachTips: ['Les coudes doivent pointer vers le plafond et ne pas bouger.'],
    commonMistakes: ['Bouger les coudes', 'Utiliser trop de charge et stresser les coudes'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  // JAMBES
  {
    id: 'squat',
    name: 'Squat',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'hamstrings', 'lower_back', 'abs'],
    primaryMuscle: 'quads',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    description: 'Le roi des exercices pour les jambes. Mouvement polyarticulaire fondamental.',
    instructions: [
      'Barre sur la nuque (haut du dos), pieds dans l\'axe des épaules ou légèrement plus larges.',
      'Pointes des pieds légèrement vers l\'extérieur.',
      'Descends en poussant les genoux dans l\'axe des pieds.',
      'Descends jusqu\'à ce que les cuisses soient parallèles au sol minimum.',
      'Remonte en poussant dans le sol.',
    ],
    coachTips: [
      'Garde la poitrine haute et le dos droit.',
      'Les genoux ne doivent pas dépasser les orteils de trop.',
      'Inspire en descendant, expire en montant.',
    ],
    commonMistakes: ['Genoux qui s\'effondrent vers l\'intérieur', 'Talon qui se lève', 'Dos qui s\'arrondit'],
    defaultSets: 4,
    defaultReps: 8,
    defaultRest: 180,
  },
  {
    id: 'leg_press',
    name: 'Presse à Cuisses',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    primaryMuscle: 'quads',
    equipment: ['machine'],
    difficulty: 'beginner',
    description: 'Alternative à la machine pour travailler les jambes avec moins de contrainte sur le dos.',
    instructions: [
      'Assis dans la machine, pieds à plat sur la plateforme.',
      'Déverrouille les sécurités et fléchis les genoux.',
      'Descends jusqu\'à 90° environ.',
      'Repousse la plateforme sans verrouiller les genoux.',
    ],
    coachTips: ['La position des pieds modifie les muscles ciblés.', 'Ne verrouille jamais les genoux en haut.'],
    commonMistakes: ['Décoller les fesses du siège', 'Verrouiller les genoux', 'Genoux qui s\'effondrent'],
    defaultSets: 4,
    defaultReps: 12,
    defaultRest: 90,
  },
  {
    id: 'romanian_deadlift',
    name: 'Soulevé de Terre Roumain',
    category: 'strength',
    muscleGroups: ['hamstrings', 'glutes', 'lower_back'],
    primaryMuscle: 'hamstrings',
    equipment: ['barbell', 'dumbbells'],
    difficulty: 'intermediate',
    description: 'Exercice pour les ischio-jambiers et les fessiers par excellence.',
    instructions: [
      'Debout, barre devant les cuisses.',
      'Penche-toi en avant en poussant les hanches en arrière, dos droit.',
      'Descends jusqu\'à sentir l\'étirement dans les ischio-jambiers.',
      'Remonte en contractant les fessiers.',
    ],
    coachTips: ['La barre reste proche des jambes tout au long du mouvement.', 'Pense à "casser" les hanches vers l\'arrière.'],
    commonMistakes: ['Plier trop les genoux', 'Arrondir le dos', 'Descendre trop bas'],
    defaultSets: 4,
    defaultReps: 10,
    defaultRest: 90,
  },
  {
    id: 'lunge',
    name: 'Fentes',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    primaryMuscle: 'quads',
    equipment: ['bodyweight', 'dumbbells', 'barbell'],
    difficulty: 'beginner',
    description: 'Exercice unilatéral excellent pour les jambes et l\'équilibre.',
    instructions: [
      'Debout, fais un grand pas en avant.',
      'Descends le genou arrière vers le sol.',
      'Le genou avant ne doit pas dépasser les orteils.',
      'Remonte en poussant sur le talon avant.',
    ],
    coachTips: ['Garde le buste droit tout au long.', 'Contrôle la descente.'],
    commonMistakes: ['Genou avant qui dépasse les orteils', 'Se pencher en avant', 'Pas assez grand pas'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'calf_raise',
    name: 'Montées sur la Pointe des Pieds',
    category: 'strength',
    muscleGroups: ['calves'],
    primaryMuscle: 'calves',
    equipment: ['bodyweight', 'machine'],
    difficulty: 'beginner',
    description: 'Isolation des mollets debout ou à la machine.',
    instructions: [
      'Debout sur une surface, pointe de pied sur le bord.',
      'Monte sur la pointe des pieds.',
      'Descends en dessous du niveau de la plateforme pour un étirement complet.',
    ],
    coachTips: ['Va lentement et cherche le brûlé.', 'Pause d\'une seconde en haut.'],
    commonMistakes: ['Trop vite', 'Amplitude incomplète'],
    defaultSets: 4,
    defaultReps: 15,
    defaultRest: 45,
  },
  // ABDOMINAUX
  {
    id: 'plank',
    name: 'Gainage (Planche)',
    category: 'strength',
    muscleGroups: ['abs', 'lower_back', 'shoulders'],
    primaryMuscle: 'abs',
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    description: 'Exercice de gainage isométrique fondamental pour le core.',
    instructions: [
      'En appui sur les avant-bras et les orteils.',
      'Corps parfaitement aligné.',
      'Contracte les abdos, les fessiers.',
      'Respire normalement.',
    ],
    coachTips: ['Imagine qu\'on tire une corde de ta tête à tes talons.'],
    commonMistakes: ['Hanches qui montent ou descendent', 'Regarder devant soi'],
    defaultSets: 3,
    defaultDuration: 60,
    defaultRest: 45,
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'strength',
    muscleGroups: ['abs'],
    primaryMuscle: 'abs',
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    description: 'Flexion du tronc pour cibler le droit de l\'abdomen.',
    instructions: [
      'Allongé sur le dos, genoux fléchis.',
      'Mains derrière la tête ou sur les tempes.',
      'Décolle les épaules du sol en contractant les abdos.',
      'Reviens lentement à la position initiale.',
    ],
    coachTips: ['Creux lombaire maintenu.', 'Ne tire pas sur la nuque.'],
    commonMistakes: ['Tirer sur la nuque', 'Utiliser l\'élan', 'Arrondir tout le dos'],
    defaultSets: 3,
    defaultReps: 20,
    defaultRest: 45,
  },
  {
    id: 'leg_raise',
    name: 'Relevés de Jambes',
    category: 'strength',
    muscleGroups: ['abs', 'lower_back'],
    primaryMuscle: 'abs',
    equipment: ['bodyweight', 'pull_up_bar'],
    difficulty: 'intermediate',
    description: 'Exercice pour le bas des abdominaux. Peut se faire allongé ou suspendu.',
    instructions: [
      'Allongé, bras le long du corps.',
      'Soulève les jambes tendues à 90°.',
      'Redescends lentement sans toucher le sol.',
    ],
    coachTips: ['Bas du dos collé au sol.', 'Version suspendue plus difficile et plus efficace.'],
    commonMistakes: ['Cambrer le bas du dos', 'Prendre de l\'élan'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 45,
  },
  {
    id: 'russian_twist',
    name: 'Rotations Russes',
    category: 'strength',
    muscleGroups: ['abs'],
    primaryMuscle: 'abs',
    equipment: ['bodyweight', 'dumbbells'],
    difficulty: 'beginner',
    description: 'Rotation du buste pour cibler les obliques.',
    instructions: [
      'Assis au sol, jambes fléchies soulevées légèrement.',
      'Tourne le buste de gauche à droite en touchant le sol des deux côtés.',
    ],
    coachTips: ['Plus les pieds sont hauts, plus c\'est difficile.', 'Ajoute un poids pour plus d\'intensité.'],
    commonMistakes: ['Vitesse trop rapide sans contrôle'],
    defaultSets: 3,
    defaultReps: 20,
    defaultRest: 45,
  },
  // CARDIO MUSCULATION
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'strength',
    muscleGroups: ['full_body'],
    primaryMuscle: 'full_body',
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    description: 'Exercice complet combinant force et cardio.',
    instructions: [
      'Debout, descends en position de pompe.',
      'Fais une pompe.',
      'Ramène les pieds vers les mains.',
      'Saute en l\'air en levant les bras.',
    ],
    coachTips: ['Maintiens un rythme régulier plutôt que de partir trop vite.'],
    commonMistakes: ['Oublier la pompe', 'Sauter sans engagement du core'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 90,
  },
  // MUSCULATION supplémentaire
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    category: 'strength',
    muscleGroups: ['glutes', 'hamstrings'],
    primaryMuscle: 'glutes',
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    description: 'Exercice numéro 1 pour les fessiers.',
    instructions: [
      'Dos appuyé sur le banc, barre sur les hanches.',
      'Pieds à plat, genoux à 90°.',
      'Pousse les hanches vers le haut en contractant les fessiers.',
      'Descends lentement.',
    ],
    coachTips: ['Pousse avec les talons.', 'Contracte fort les fessiers en haut pendant 1 seconde.'],
    commonMistakes: ['Arque trop le dos en haut', 'Genoux qui s\'écartent'],
    defaultSets: 4,
    defaultReps: 12,
    defaultRest: 75,
  },
  {
    id: 'hammer_curl',
    name: 'Curl Marteau',
    category: 'strength',
    muscleGroups: ['biceps', 'forearms'],
    primaryMuscle: 'biceps',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    description: 'Variante du curl ciblant le brachial et les avant-bras.',
    instructions: [
      'Haltères en prise neutre (pouces vers le haut).',
      'Fléchis les coudes alternativement ou ensemble.',
    ],
    coachTips: ['La prise neutre sollicite plus l\'avant-bras.'],
    commonMistakes: ['Balancer le buste'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'tricep_pushdown',
    name: 'Extension Triceps Poulie',
    category: 'strength',
    muscleGroups: ['triceps'],
    primaryMuscle: 'triceps',
    equipment: ['cable'],
    difficulty: 'beginner',
    description: 'Exercice d\'isolation pour les triceps à la poulie haute.',
    instructions: [
      'Debout face à la poulie haute avec une barre ou corde.',
      'Coudes contre le corps, pousse vers le bas.',
      'Contracte les triceps en bas.',
      'Remonte contrôlément.',
    ],
    coachTips: ['Les coudes restent fixes tout au long.'],
    commonMistakes: ['Lever les coudes', 'Se pencher trop en avant'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'goblet_squat',
    name: 'Squat Gobelet',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'abs'],
    primaryMuscle: 'quads',
    equipment: ['kettlebell', 'dumbbells'],
    difficulty: 'beginner',
    description: 'Version accessoire du squat, parfaite pour apprendre la technique.',
    instructions: [
      'Tiens un kettlebell ou haltère contre la poitrine.',
      'Descends en squat profond.',
      'Remonte en poussant dans les talons.',
    ],
    coachTips: ['Le poids devant aide à garder le buste droit.'],
    commonMistakes: ['Ne pas descendre assez bas'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Développé Épaules Haltères',
    category: 'strength',
    muscleGroups: ['shoulders', 'triceps'],
    primaryMuscle: 'shoulders',
    equipment: ['dumbbells', 'bench'],
    difficulty: 'beginner',
    description: 'Presse verticale aux haltères pour les épaules.',
    instructions: [
      'Assis, haltères à hauteur des épaules, paumes vers l\'avant.',
      'Pousse au-dessus de la tête.',
      'Redescends contrôlément.',
    ],
    coachTips: ['Version unilatérale possible pour corriger les déséquilibres.'],
    commonMistakes: ['Cambrer le dos', 'Pousser devant soi'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 75,
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Curl Incliné Haltères',
    category: 'strength',
    muscleGroups: ['biceps'],
    primaryMuscle: 'biceps',
    equipment: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    description: 'Curl avec étirement maximal des biceps sur banc incliné.',
    instructions: [
      'Assis sur banc incliné à 45-60°.',
      'Laisse les bras pendre derrière toi.',
      'Fléchis les coudes en supinant les mains.',
    ],
    coachTips: ['L\'étirement en bas est la clé de cet exercice.'],
    commonMistakes: ['Banc trop incliné', 'Monter les coudes'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'front_squat',
    name: 'Squat Avant',
    category: 'strength',
    muscleGroups: ['quads', 'abs', 'shoulders'],
    primaryMuscle: 'quads',
    equipment: ['barbell'],
    difficulty: 'advanced',
    description: 'Squat avec barre devant, cible plus les quadriceps.',
    instructions: [
      'Barre sur les clavicules, coudes hauts.',
      'Descends en squat avec le buste bien droit.',
    ],
    coachTips: ['Coudes hauts pour maintenir la barre en place.'],
    commonMistakes: ['Coudes qui tombent', 'Buste qui s\'incline trop en avant'],
    defaultSets: 4,
    defaultReps: 6,
    defaultRest: 150,
  },
  {
    id: 'cable_curl',
    name: 'Curl Poulie',
    category: 'strength',
    muscleGroups: ['biceps'],
    primaryMuscle: 'biceps',
    equipment: ['cable'],
    difficulty: 'beginner',
    description: 'Curl à la poulie basse pour une tension constante sur les biceps.',
    instructions: [
      'Face à la poulie basse, prends la barre.',
      'Fléchis les coudes en tirant vers les épaules.',
    ],
    coachTips: ['Tension constante tout au long du mouvement.'],
    commonMistakes: ['Balancer le corps'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'sumo_deadlift',
    name: 'Soulevé de Terre Sumo',
    category: 'strength',
    muscleGroups: ['glutes', 'quads', 'hamstrings', 'lower_back'],
    primaryMuscle: 'glutes',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    description: 'Variante du soulevé de terre avec prise large, plus de fessiers.',
    instructions: [
      'Pieds très écartés, pointes vers l\'extérieur.',
      'Prise étroite, intérieur des mains.',
      'Soulève en poussant les genoux dans l\'axe des pieds.',
    ],
    coachTips: ['Idéal pour les personnes avec un dos sensible.'],
    commonMistakes: ['Genoux qui s\'effondrent', 'Dos arrondi'],
    defaultSets: 4,
    defaultReps: 6,
    defaultRest: 150,
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    category: 'strength',
    muscleGroups: ['shoulders', 'triceps'],
    primaryMuscle: 'shoulders',
    equipment: ['dumbbells'],
    difficulty: 'intermediate',
    description: 'Variante de la presse épaules créée par Arnold Schwarzenegger.',
    instructions: [
      'Commence comme un curl en haut (paumes vers toi).',
      'Tourne les paumes vers l\'extérieur en montant.',
      'Presse jusqu\'en haut.',
    ],
    coachTips: ['Le mouvement de rotation active toutes les têtes du deltoïde.'],
    commonMistakes: ['Mouvement de rotation trop rapide'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 75,
  },
  {
    id: 'cable_flyes',
    name: 'Écarté Poulie',
    category: 'strength',
    muscleGroups: ['chest'],
    primaryMuscle: 'chest',
    equipment: ['cable'],
    difficulty: 'intermediate',
    description: 'Version poulie des écartés pour une tension constante.',
    instructions: [
      'Deux poulies basses ou hautes selon l\'angle voulu.',
      'Mouvement en arc de cercle vers le centre.',
    ],
    coachTips: ['Variation de l\'angle change le ciblage des pectoraux.'],
    commonMistakes: ['Trop de charge', 'Mouvement saccadé'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'bent_over_lateral_raise',
    name: 'Oiseau (Élévation Penchée)',
    category: 'strength',
    muscleGroups: ['shoulders', 'back'],
    primaryMuscle: 'shoulders',
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    description: 'Isolation du deltoïde postérieur, essentiel pour les épaules équilibrées.',
    instructions: [
      'Penché à 45-90°.',
      'Lève les haltères latéralement.',
    ],
    coachTips: ['Le coude légèrement fléchi, pince l\'omoplate en haut.'],
    commonMistakes: ['Trop se relever pendant le mouvement'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  // Exercices supplémentaires musculation
  {
    id: 'good_morning',
    name: 'Good Morning',
    category: 'strength',
    muscleGroups: ['lower_back', 'hamstrings', 'glutes'],
    primaryMuscle: 'lower_back',
    equipment: ['barbell'],
    difficulty: 'intermediate',
    description: 'Renforcement de la chaîne postérieure, particulièrement les lombaires.',
    instructions: [
      'Barre sur la nuque, pieds dans l\'axe des épaules.',
      'Penche le buste en avant en gardant le dos droit.',
      'Descends jusqu\'à ce que le buste soit parallèle au sol.',
    ],
    coachTips: ['Commence léger pour maîtriser la technique.'],
    commonMistakes: ['Arrondir le dos', 'Fléchir trop les genoux'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 75,
  },
  {
    id: 'seated_leg_curl',
    name: 'Leg Curl Assis',
    category: 'strength',
    muscleGroups: ['hamstrings'],
    primaryMuscle: 'hamstrings',
    equipment: ['machine'],
    difficulty: 'beginner',
    description: 'Isolation des ischio-jambiers à la machine.',
    instructions: [
      'Assis dans la machine, cheville sous le coussin.',
      'Fléchis les genoux en tirant vers les fessiers.',
    ],
    coachTips: ['Contrôle la phase excentrique.'],
    commonMistakes: ['Trop de charge', 'Vitesse excessive'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'dips_bench',
    name: 'Dips sur Banc',
    category: 'strength',
    muscleGroups: ['triceps', 'chest'],
    primaryMuscle: 'triceps',
    equipment: ['bench', 'bodyweight'],
    difficulty: 'beginner',
    description: 'Version facile des dips avec les pieds au sol.',
    instructions: [
      'Mains sur le bord du banc, pieds devant toi.',
      'Descends les fesses vers le sol en fléchissant les coudes.',
      'Remonte.',
    ],
    coachTips: ['Pour augmenter la difficulté, pose les pieds sur un banc en face.'],
    commonMistakes: ['Trop s\'éloigner du banc', 'Descendre trop bas'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'chest_press_machine',
    name: 'Développé Couché Machine',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    primaryMuscle: 'chest',
    equipment: ['machine'],
    difficulty: 'beginner',
    description: 'Alternative sécurisée au développé couché à la barre.',
    instructions: [
      'Assis, poitrine face aux poignées.',
      'Pousse devant toi.',
      'Reviens lentement.',
    ],
    coachTips: ['Parfait pour finir une séance pectoraux ou pour les débutants.'],
    commonMistakes: ['Épaules qui montent', 'Trop vite en excentrique'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'wrist_curl',
    name: 'Curl Poignets',
    category: 'strength',
    muscleGroups: ['forearms'],
    primaryMuscle: 'forearms',
    equipment: ['barbell', 'dumbbells'],
    difficulty: 'beginner',
    description: 'Renforcement des avant-bras et amélioration de la prise.',
    instructions: [
      'Assis, avant-bras sur les cuisses, poignets au bord des genoux.',
      'Fléchis et étends les poignets.',
    ],
    coachTips: ['Amplitude complète pour de bons résultats.'],
    commonMistakes: ['Trop de charge, petite amplitude'],
    defaultSets: 3,
    defaultReps: 20,
    defaultRest: 45,
  },
  {
    id: 'mountain_climber',
    name: 'Grimpeur de Montagne',
    category: 'strength',
    muscleGroups: ['abs', 'full_body'],
    primaryMuscle: 'abs',
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    description: 'Exercice dynamique pour le core et le cardio.',
    instructions: [
      'En position de planche haute.',
      'Ramène alternativement les genoux vers la poitrine.',
    ],
    coachTips: ['Plus vite = plus de cardio. Plus lentement = plus de core.'],
    commonMistakes: ['Hanches qui montent trop haut', 'Pas de gainage du core'],
    defaultSets: 3,
    defaultDuration: 30,
    defaultRest: 45,
  },
  {
    id: 'cable_row_single_arm',
    name: 'Rowing Unilatéral Poulie',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    primaryMuscle: 'back',
    equipment: ['cable'],
    difficulty: 'beginner',
    description: 'Rowing unilatéral pour corriger les déséquilibres musculaires.',
    instructions: [
      'Face à la poulie basse, un genou sur le banc.',
      'Tire avec un bras en ramenant le coude vers la hanche.',
    ],
    coachTips: ['Rotation légère du buste pour plus d\'amplitude.'],
    commonMistakes: ['Trop de rotation du buste', 'Soulever l\'épaule'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'lying_leg_curl',
    name: 'Leg Curl Allongé',
    category: 'strength',
    muscleGroups: ['hamstrings'],
    primaryMuscle: 'hamstrings',
    equipment: ['machine'],
    difficulty: 'beginner',
    description: 'Isolation des ischio-jambiers allongé.',
    instructions: [
      'Allongé sur la machine, cheville sous le coussin.',
      'Ramène les talons vers les fesses.',
    ],
    coachTips: ['Évite de décoller les hanches.'],
    commonMistakes: ['Hanches qui se soulèvent', 'Descente trop rapide'],
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Squat Bulgare',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    primaryMuscle: 'quads',
    equipment: ['bodyweight', 'dumbbells', 'bench'],
    difficulty: 'intermediate',
    description: 'Squat unilatéral très efficace pour jambes et fessiers.',
    instructions: [
      'Pied arrière posé sur un banc.',
      'Pied avant devant, descends comme une fente.',
      'Genou arrière vers le sol.',
    ],
    coachTips: ['Excellent pour corriger les déséquilibres gauche/droite.'],
    commonMistakes: ['Trop loin ou trop proche du banc', 'Genou qui s\'effondre'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 75,
  },
  {
    id: 'incline_pushup',
    name: 'Pompes Inclinées',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    primaryMuscle: 'chest',
    equipment: ['bodyweight', 'bench'],
    difficulty: 'beginner',
    description: 'Pompes avec les mains surélevées, version plus facile.',
    instructions: [
      'Mains sur un banc ou une chaise.',
      'Corps aligné, descends les pectoraux vers l\'appui.',
    ],
    coachTips: ['Plus les mains sont hautes, plus c\'est facile.'],
    commonMistakes: ['Hanches qui s\'affaissent'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'close_grip_bench_press',
    name: 'Développé Couché Prise Serrée',
    category: 'strength',
    muscleGroups: ['triceps', 'chest'],
    primaryMuscle: 'triceps',
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    description: 'Variante du développé couché ciblant principalement les triceps.',
    instructions: [
      'Prise serrée (mains à la largeur des épaules).',
      'Coudes le long du corps durant tout le mouvement.',
    ],
    coachTips: ['Évite de trop resserrer les mains, les poignets seraient mal positionnés.'],
    commonMistakes: ['Prise trop serrée', 'Coudes qui s\'écartent'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 75,
  },
  // FOOTBALL
  {
    id: 'sprint_10m',
    name: 'Sprint 10m',
    category: 'football',
    muscleGroups: ['quads', 'hamstrings', 'calves'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Sprint court pour développer l\'accélération et l\'explosivité.',
    instructions: [
      'Position de départ basse.',
      'Explode vers l\'avant, bras qui pompent.',
      'Incline le buste en avant les premières foulées.',
    ],
    coachTips: ['La phase d\'accélération est la plus importante. Prise de terre sous le centre de gravité.'],
    commonMistakes: ['Se redresser trop tôt', 'Foulées trop courtes'],
    defaultSets: 6,
    defaultDuration: 5,
    defaultRest: 90,
  },
  {
    id: 'agility_ladder',
    name: 'Échelle de Vitesse',
    category: 'football',
    muscleGroups: ['calves', 'quads', 'full_body'],
    primaryMuscle: 'calves',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Exercices de coordination et d\'agilité pour le football.',
    instructions: [
      'Traverse l\'échelle en variant les patterns.',
      'Deux pieds dans chaque case, un pied, latéral, etc.',
    ],
    coachTips: ['Commence lentement et accélère progressivement.', 'Reste sur la pointe des pieds.'],
    commonMistakes: ['Regarder les pieds', 'Perdre la rapidité des bras'],
    defaultSets: 4,
    defaultDuration: 20,
    defaultRest: 60,
  },
  {
    id: 'cone_slalom',
    name: 'Slalom Plots',
    category: 'football',
    muscleGroups: ['quads', 'calves', 'full_body'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Exercice de changement de direction entre des plots.',
    instructions: [
      'Place 5 plots espacés de 2m.',
      'Slalome entre les plots à pleine vitesse.',
      'Retour au point de départ.',
    ],
    coachTips: ['Centre de gravité bas dans les virages.'],
    commonMistakes: ['Ralentir trop avant le plot', 'Appuis trop larges'],
    defaultSets: 5,
    defaultDuration: 15,
    defaultRest: 45,
  },
  {
    id: 'football_juggling',
    name: 'Jonglerie Ballon',
    category: 'football',
    muscleGroups: ['full_body'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Développement du toucher de balle et de la coordination.',
    instructions: [
      'Jongle avec le pied, la cuisse, la tête.',
      'Essaie de ne pas laisser tomber le ballon.',
    ],
    coachTips: ['Commence par des touches courtes et simples.'],
    commonMistakes: ['Regarder trop haut', 'Frapper trop fort'],
    defaultSets: 3,
    defaultDuration: 60,
    defaultRest: 30,
  },
  {
    id: 'box_jump',
    name: 'Saut sur Box',
    category: 'football',
    muscleGroups: ['quads', 'glutes', 'calves'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Exercice pliométrique pour développer l\'explosivité des jambes.',
    instructions: [
      'Face à une box, pieds dans l\'axe des épaules.',
      'Fléchis légèrement puis explose vers la box.',
      'Atterris doucement en fléchissant les genoux.',
    ],
    coachTips: ['L\'atterrissage est aussi important que le saut.'],
    commonMistakes: ['Atterrir jambes tendues', 'Trop grande box dès le départ'],
    defaultSets: 4,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'passing_drill',
    name: 'Exercice de Passe',
    category: 'football',
    muscleGroups: ['full_body'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Perfectionnement de la technique de passe à différentes distances.',
    instructions: [
      'Passe courte : intérieur du pied.',
      'Passe longue : coup de pied.',
      'Varier les distances et les angles.',
    ],
    coachTips: ['Appui stable avant la frappe.'],
    commonMistakes: ['Frapper de la pointe', 'Mauvais placement du corps'],
    defaultSets: 3,
    defaultDuration: 120,
    defaultRest: 30,
  },
  {
    id: 'speed_dribbling',
    name: 'Dribble Vitesse',
    category: 'football',
    muscleGroups: ['full_body'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Conduite de balle à grande vitesse sur un couloir.',
    instructions: [
      'Conduis le ballon sur 30m à pleine vitesse.',
      'Utilise l\'extérieur du pied dominant.',
    ],
    coachTips: ['Garde la tête levée pour anticiper.'],
    commonMistakes: ['Trop de touches', 'Balle trop loin devant soi'],
    defaultSets: 6,
    defaultDuration: 30,
    defaultRest: 60,
  },
  {
    id: 'reaction_drill',
    name: 'Exercice de Réactivité',
    category: 'football',
    muscleGroups: ['full_body'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Améliore le temps de réaction et les changements de direction.',
    instructions: [
      'Partenaire ou signal sonore.',
      'Démarre et change de direction sur signal.',
    ],
    coachTips: ['Position d\'attente athlétique, prêt à partir dans toutes les directions.'],
    commonMistakes: ['Position d\'attente trop haute'],
    defaultSets: 5,
    defaultDuration: 10,
    defaultRest: 60,
  },
  {
    id: 'heading_practice',
    name: 'Jeu de Tête',
    category: 'football',
    muscleGroups: ['shoulders', 'abs', 'full_body'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Technique du jeu de tête défensif et offensif.',
    instructions: [
      'Frappe le ballon avec le front (pas le sommet du crâne).',
      'Genoux légèrement fléchis, mouvement des hanches pour la puissance.',
    ],
    coachTips: ['Garde les yeux ouverts jusqu\'à l\'impact.'],
    commonMistakes: ['Fermer les yeux', 'Frapper avec le crâne'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 30,
  },
  {
    id: 'lateral_sprint',
    name: 'Sprints Latéraux',
    category: 'football',
    muscleGroups: ['quads', 'hamstrings', 'calves', 'glutes'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Travail de déplacement latéral pour la défense et le pressing.',
    instructions: [
      'Déplacement latéral en pas chassé sur 10m.',
      'Reste bas, pieds qui ne se croisent pas.',
    ],
    coachTips: ['Centre de gravité bas.', 'Revenir vite à la position centrale.'],
    commonMistakes: ['Croiser les pieds', 'Se redresser'],
    defaultSets: 5,
    defaultDuration: 20,
    defaultRest: 45,
  },
  {
    id: 'shooting_technique',
    name: 'Technique de Frappe',
    category: 'football',
    muscleGroups: ['quads', 'hamstrings', 'glutes'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Travail de la technique de frappe au but.',
    instructions: [
      'Placement du pied d\'appui à côté du ballon.',
      'Frappe avec le cou-de-pied pour la précision.',
      'Frappe avec le coup de pied pour la puissance.',
    ],
    coachTips: ['Le pied d\'appui pointe vers la cible.'],
    commonMistakes: ['Pied d\'appui trop loin', 'Reculer après la frappe'],
    defaultSets: 4,
    defaultReps: 10,
    defaultRest: 30,
  },
  {
    id: 'press_up_explosive',
    name: 'Pompes Explosives',
    category: 'football',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    primaryMuscle: 'chest',
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    description: 'Pompes avec poussée explosive pour développer la puissance des bras.',
    instructions: [
      'Pompe normale jusqu\'en bas.',
      'Pousse explosément pour décoller les mains du sol.',
    ],
    coachTips: ['Gainage du core indispensable.'],
    commonMistakes: ['Pas assez explosif', 'Gainage insuffisant'],
    defaultSets: 4,
    defaultReps: 8,
    defaultRest: 75,
  },
  {
    id: 'ball_control',
    name: 'Contrôle de Balle',
    category: 'football',
    muscleGroups: ['full_body'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Exercices de contrôle du ballon de toutes les surfaces.',
    instructions: [
      'Lancer le ballon en l\'air et contrôler avec différentes surfaces.',
      'Intérieur, extérieur, dos du pied, poitrine, cuisse.',
    ],
    coachTips: ['Amortis le ballon en retirant la surface de contact.'],
    commonMistakes: ['Surface rigide au moment du contact', 'Mauvais angle'],
    defaultSets: 3,
    defaultDuration: 90,
    defaultRest: 30,
  },
  {
    id: 'interval_run_football',
    name: 'Course Intervalles Football',
    category: 'football',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Simulation des efforts intermittents d\'un match de football.',
    instructions: [
      '3 min jogging, 1 min sprint x 5.',
      'Reproduit l\'effort d\'un match.',
    ],
    coachTips: ['Adapte les vitesses à ton niveau.'],
    commonMistakes: ['Trop vite dès le début'],
    defaultSets: 5,
    defaultDuration: 240,
    defaultRest: 60,
  },
  // RUGBY
  {
    id: 'scrum_push',
    name: 'Poussée en Mêlée',
    category: 'rugby',
    muscleGroups: ['back', 'shoulders', 'quads', 'glutes'],
    primaryMuscle: 'back',
    equipment: ['none'],
    difficulty: 'advanced',
    description: 'Simulation de la poussée en mêlée pour développer la force collective.',
    instructions: [
      'Position basse, dos plat, poussée horizontale.',
      'Travail en groupe ou contre un sac de plaquage.',
    ],
    coachTips: ['La position des pieds est cruciale. Pieds en largeur des épaules.'],
    commonMistakes: ['Dos arrondi', 'Poussée vers le haut plutôt qu\'horizontale'],
    defaultSets: 4,
    defaultDuration: 15,
    defaultRest: 90,
  },
  {
    id: 'tackle_bag',
    name: 'Plaquage sur Sac',
    category: 'rugby',
    muscleGroups: ['shoulders', 'back', 'quads'],
    primaryMuscle: 'shoulders',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Technique de plaquage sur sac de plaquage.',
    instructions: [
      'Approche du sac en bonne position.',
      'Contact épaule, tête à côté.',
      'Enroulement des bras et poussée.',
    ],
    coachTips: ['Tête toujours à côté, jamais devant.'],
    commonMistakes: ['Tête en avant', 'Perdre ses appuis'],
    defaultSets: 4,
    defaultReps: 6,
    defaultRest: 90,
  },
  {
    id: 'rugby_sprint',
    name: 'Sprint Rugby',
    category: 'rugby',
    muscleGroups: ['quads', 'hamstrings', 'calves'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Sprint court et puissant comme lors d\'un départ de mêlée ou d\'un crochet.',
    instructions: [
      'Départ depuis position basse de joueur.',
      'Sprint 20-30m à intensité maximale.',
    ],
    coachTips: ['L\'accélération est plus importante que la vitesse de pointe au rugby.'],
    commonMistakes: ['Départ trop haut'],
    defaultSets: 6,
    defaultDuration: 8,
    defaultRest: 120,
  },
  {
    id: 'catching_drill',
    name: 'Exercice de Réception',
    category: 'rugby',
    muscleGroups: ['shoulders', 'full_body'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Technique de réception du ballon ovale.',
    instructions: [
      'Forme un W avec les mains pour les passes hautes.',
      'Forme un triangle pour les passes basses.',
      'Yeux sur le ballon jusqu\'à la réception.',
    ],
    coachTips: ['Amortis le ballon en retirant légèrement les mains à l\'impact.'],
    commonMistakes: ['Mains tendues et rigides', 'Fermer les yeux'],
    defaultSets: 4,
    defaultReps: 10,
    defaultRest: 30,
  },
  {
    id: 'lineout_jump',
    name: 'Saut en Touche',
    category: 'rugby',
    muscleGroups: ['quads', 'calves', 'full_body'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Saut pour la touche, développe la détente verticale.',
    instructions: [
      'Deux porteurs de côté, sauteur au milieu.',
      'Saut vertical maximal, corps stable dans les airs.',
    ],
    coachTips: ['Timing avec les porteurs est crucial.'],
    commonMistakes: ['Sauter trop tôt ou trop tard'],
    defaultSets: 5,
    defaultReps: 5,
    defaultRest: 90,
  },
  {
    id: 'power_clean',
    name: 'Épaulé de Force',
    category: 'rugby',
    muscleGroups: ['full_body', 'shoulders', 'back', 'quads'],
    primaryMuscle: 'full_body',
    equipment: ['barbell'],
    difficulty: 'advanced',
    description: 'Mouvement olympique pour développer la puissance explosive globale.',
    instructions: [
      'Barre au sol comme un soulevé de terre.',
      'Tirage rapide puis rotation des coudes pour attraper la barre sur les clavicules.',
    ],
    coachTips: ['Incontournable pour les joueurs de rugby. Développe l\'explosivité.'],
    commonMistakes: ['Traction trop tôt avec les bras', 'Pas assez de vitesse'],
    defaultSets: 4,
    defaultReps: 4,
    defaultRest: 180,
  },
  {
    id: 'neck_strengthening',
    name: 'Renforcement Nuque',
    category: 'rugby',
    muscleGroups: ['back', 'shoulders'],
    primaryMuscle: 'back',
    equipment: ['bodyweight', 'resistance_band'],
    difficulty: 'beginner',
    description: 'Renforcement essentiel pour la prévention des blessures au rugby.',
    instructions: [
      'Mouvements lents de résistance dans toutes les directions.',
      'Flexion, extension, rotation latérale.',
    ],
    coachTips: ['Indispensable avant toute séance de contact.'],
    commonMistakes: ['Mouvements trop rapides', 'Amplitude excessive'],
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 30,
  },
  {
    id: 'sled_push',
    name: 'Poussée de Traîneau',
    category: 'rugby',
    muscleGroups: ['quads', 'glutes', 'back', 'shoulders'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Développe la puissance de poussée spécifique au rugby.',
    instructions: [
      'Saisit les poignées du traîneau, corps incliné en avant.',
      'Pousse avec les jambes à grande foulée.',
    ],
    coachTips: ['Corps bien incliné, pas de dos arrondi.'],
    commonMistakes: ['Trop droit', 'Petites foulées'],
    defaultSets: 5,
    defaultDuration: 20,
    defaultRest: 120,
  },
  {
    id: 'rugby_fitness',
    name: 'Beep Test',
    category: 'rugby',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'advanced',
    description: 'Test de condition physique aérobie utilisé en rugby professionnel.',
    instructions: [
      'Course navette 20m au signal sonore.',
      'Vitesse augmente progressivement.',
    ],
    coachTips: ['Viser minimum niveau 12 pour un niveau régional.'],
    commonMistakes: ['Partir trop vite', 'Mauvais virages'],
    defaultSets: 1,
    defaultDuration: 1200,
    defaultRest: 300,
  },
  {
    id: 'wrestling_drill',
    name: 'Exercice de Contact',
    category: 'rugby',
    muscleGroups: ['full_body', 'shoulders', 'back'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'advanced',
    description: 'Travail de contact et de lutte au sol.',
    instructions: [
      'Deux joueurs se font face.',
      'Travail de poussée, pulling, résistance.',
    ],
    coachTips: ['Toujours avec protection.'],
    commonMistakes: ['Pas de protection', 'Technique bâclée'],
    defaultSets: 4,
    defaultDuration: 20,
    defaultRest: 90,
  },
  {
    id: 'ruck_technique',
    name: 'Technique de Ruck',
    category: 'rugby',
    muscleGroups: ['full_body', 'back', 'quads'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Technique d\'entrée dans un ruck.',
    instructions: [
      'Approche basse.',
      'Contact dos à dos avec l\'adversaire.',
      'Poussée des jambes pour dégager le ballon.',
    ],
    coachTips: ['Toujours arriver au ruck avec de la vitesse.'],
    commonMistakes: ['Arriver debout', 'Ne pas binder correctement'],
    defaultSets: 5,
    defaultReps: 5,
    defaultRest: 90,
  },
  {
    id: 'bounding',
    name: 'Bonds (Plyométrie)',
    category: 'rugby',
    muscleGroups: ['quads', 'calves', 'glutes'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Bonds horizontaux pour développer la puissance des jambes.',
    instructions: [
      'Sauts horizontaux successifs à une ou deux jambes.',
      'Atterrissage amorti, redépart immédiat.',
    ],
    coachTips: ['Minimise le temps de contact avec le sol.'],
    commonMistakes: ['Trop de temps au sol', 'Mauvais amorti'],
    defaultSets: 4,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'kicking_practice',
    name: 'Travail du Pied',
    category: 'rugby',
    muscleGroups: ['quads', 'hamstrings'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Différentes formes de coups de pied en rugby (drop, pénalité, en jeu).',
    instructions: [
      'Drop : pose le ballon et frappe au rebond.',
      'Pénalité : ballon posé sur le tee ou maintenu.',
    ],
    coachTips: ['Tête baissée jusqu\'à l\'impact.'],
    commonMistakes: ['Regarder la cible trop tôt'],
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 45,
  },
  {
    id: 'maul_simulation',
    name: 'Simulation de Maul',
    category: 'rugby',
    muscleGroups: ['full_body', 'back', 'shoulders', 'quads'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'advanced',
    description: 'Simulation de jeu en maul pour la technique et la puissance collective.',
    instructions: [
      '2v1 ou 3v2.',
      'Porteur de balle protégé par ses partenaires.',
      'Avancée en groupe.',
    ],
    coachTips: ['Communication et timing entre les joueurs.'],
    commonMistakes: ['Pas de communication', 'Corps trop haut'],
    defaultSets: 4,
    defaultDuration: 30,
    defaultRest: 90,
  },
  {
    id: 'passing_off_hands',
    name: 'Passe de la Main (Rugby)',
    category: 'rugby',
    muscleGroups: ['shoulders', 'forearms'],
    primaryMuscle: 'shoulders',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Technique de passe au rugby, des deux mains.',
    instructions: [
      'Prise du ballon des deux mains.',
      'Rotation des hanches et épaules.',
      'Suivi de mains vers la cible.',
    ],
    coachTips: ['La passe vient des hanches, pas seulement des bras.'],
    commonMistakes: ['Passe que du bras', 'Ballon qui tourne mal'],
    defaultSets: 3,
    defaultReps: 20,
    defaultRest: 30,
  },
  // CARDIO
  {
    id: 'running_steady',
    name: 'Course Endurance',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Course à pied à allure modérée pour développer l\'endurance aérobie.',
    instructions: [
      'Allure conversationnelle (tu peux parler).',
      'Foulée régulière, bras décontractés.',
      'Respiration nasale/buccale selon l\'intensité.',
    ],
    coachTips: ['La constance est plus importante que la vitesse.', 'Commence par 20 min et augmente de 10% par semaine.'],
    commonMistakes: ['Partir trop vite', 'Respiration anarchique'],
    defaultSets: 1,
    defaultDuration: 1800,
    defaultRest: 0,
  },
  {
    id: 'hiit_sprint',
    name: 'HIIT Sprint',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'advanced',
    description: 'Intervalles haute intensité : 30s sprint / 30s marche.',
    instructions: [
      '10 min d\'échauffement.',
      '30s sprint à fond.',
      '30s marche ou jogging léger.',
      'Répéter 8-12 fois.',
    ],
    coachTips: ['Moins de séances mais plus efficaces pour la perte de poids.'],
    commonMistakes: ['Pas assez intense pendant les sprints', 'Sauter l\'échauffement'],
    defaultSets: 10,
    defaultDuration: 30,
    defaultRest: 30,
  },
  {
    id: 'jump_rope',
    name: 'Corde à Sauter',
    category: 'cardio',
    muscleGroups: ['calves', 'shoulders', 'full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Excellent cardio facile à faire partout, développe la coordination.',
    instructions: [
      'Corde ajustée à ta taille.',
      'Sauts légers sur la pointe des pieds.',
      'Poignets qui tournent, pas les épaules.',
    ],
    coachTips: ['Commence par des séries de 30s et augmente progressivement.'],
    commonMistakes: ['Sauter trop haut', 'Utiliser les épaules'],
    defaultSets: 5,
    defaultDuration: 60,
    defaultRest: 30,
  },
  {
    id: 'cycling',
    name: 'Vélo / Vélo Stationnaire',
    category: 'cardio',
    muscleGroups: ['quads', 'hamstrings', 'calves', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Cardio à faible impact articulaire, idéal pour la récupération active.',
    instructions: [
      'Selle réglée pour que la jambe soit presque tendue en bas.',
      'Cadence : 70-90 tours/min.',
    ],
    coachTips: ['Excellent pour la récupération active entre deux séances.'],
    commonMistakes: ['Selle trop basse', 'Cadence trop lente avec gros développement'],
    defaultSets: 1,
    defaultDuration: 1800,
    defaultRest: 0,
  },
  {
    id: 'rowing_machine',
    name: 'Rameur',
    category: 'cardio',
    muscleGroups: ['back', 'shoulders', 'quads', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['machine'],
    difficulty: 'intermediate',
    description: 'Cardio sollicitant tout le corps, excellent pour le dos et les jambes.',
    instructions: [
      'Séquence : jambes → tronc → bras pour la traction.',
      'Retour : bras → tronc → jambes.',
    ],
    coachTips: ['Les jambes font 60% du travail.'],
    commonMistakes: ['Commencer par les bras', 'Dos arrondi'],
    defaultSets: 1,
    defaultDuration: 1200,
    defaultRest: 0,
  },
  {
    id: 'stair_climbing',
    name: 'Montée d\'Escaliers',
    category: 'cardio',
    muscleGroups: ['quads', 'glutes', 'calves', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Cardio naturel qui renforce les jambes et fait travailler le cœur.',
    instructions: [
      'Monte les escaliers à un rythme soutenu.',
      'Varie : un marche à la fois, deux, en courant...',
    ],
    coachTips: ['Pousse sur les orteils pour cibler les mollets.'],
    commonMistakes: ['Regarder ses pieds', 'Pas de pompe des bras'],
    defaultSets: 5,
    defaultDuration: 60,
    defaultRest: 30,
  },
  {
    id: 'swimming',
    name: 'Natation',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Sport complet à zéro impact articulaire.',
    instructions: [
      'Crawl pour l\'endurance, dos crawl pour la récupération.',
      'Alterne nages et styles.',
    ],
    coachTips: ['Excellent pour la récupération après une blessure.'],
    commonMistakes: ['Nager sans technique', 'Mauvaise respiration'],
    defaultSets: 1,
    defaultDuration: 1800,
    defaultRest: 0,
  },
  {
    id: 'tabata',
    name: 'Tabata',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    description: 'Protocole HIIT 20s travail / 10s repos x 8 = 4 min.',
    instructions: [
      '20s d\'effort maximal (burpees, squat jump, etc.).',
      '10s de repos.',
      '8 rounds = 4 minutes.',
    ],
    coachTips: ['Très court mais très intense. Énergivore.'],
    commonMistakes: ['Pas assez intense pendant les 20s'],
    defaultSets: 8,
    defaultDuration: 20,
    defaultRest: 10,
  },
  {
    id: 'elliptical',
    name: 'Elliptique',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['machine'],
    difficulty: 'beginner',
    description: 'Cardio à faible impact qui simule la course sans l\'impact.',
    instructions: [
      'Cadence régulière.',
      'Utilise les bras pour solliciter le haut du corps.',
    ],
    coachTips: ['Inclinaison = plus de fessiers. Résistance = plus de force.'],
    commonMistakes: ['S\'appuyer sur les barres', 'Pas utiliser les bras'],
    defaultSets: 1,
    defaultDuration: 1800,
    defaultRest: 0,
  },
  {
    id: 'circuit_training',
    name: 'Circuit Training',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    description: 'Enchaînement d\'exercices sans temps de repos entre chaque.',
    instructions: [
      'Pompes x15 → Squats x20 → Crunch x20 → Burpees x10.',
      'Repos 2 min entre les tours.',
      '3-5 tours.',
    ],
    coachTips: ['Allier force et cardio dans un seul entraînement.'],
    commonMistakes: ['Mauvaise organisation des exercices', 'Repos trop longs'],
    defaultSets: 3,
    defaultDuration: 600,
    defaultRest: 120,
  },
  {
    id: 'shadow_boxing',
    name: 'Shadow Boxing',
    category: 'cardio',
    muscleGroups: ['shoulders', 'full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Boxe dans le vide pour le cardio et la coordination.',
    instructions: [
      'Garde les poings levés.',
      'Frappe (jab, cross, crochet) en te déplaçant.',
    ],
    coachTips: ['Garde la garde haute même quand tu es fatigué.'],
    commonMistakes: ['Baisser la garde', 'S\'arrêter de bouger'],
    defaultSets: 5,
    defaultDuration: 120,
    defaultRest: 30,
  },
  {
    id: 'fartlek',
    name: 'Fartlek',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardio'],
    primaryMuscle: 'cardio',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Course avec variations d\'allure libres, entre jogging et sprint.',
    instructions: [
      'Jog de base.',
      'Sprint de poteau en poteau ou 30s.',
      'Retour au jogging.',
      'Répéter librement.',
    ],
    coachTips: ['Moins structuré que le HIIT, plus naturel.'],
    commonMistakes: ['Sprints trop longs', 'Récupération insuffisante'],
    defaultSets: 1,
    defaultDuration: 1800,
    defaultRest: 0,
  },
  // ÉTIREMENTS
  {
    id: 'quad_stretch',
    name: 'Étirement Quadriceps',
    category: 'stretching',
    muscleGroups: ['quads'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Étirement statique des quadriceps debout.',
    instructions: [
      'Debout, plie le genou et amène le pied vers les fesses.',
      'Maintiens la cheville de la même main.',
      'Genoux serrés l\'un contre l\'autre.',
    ],
    coachTips: ['Utilise un mur pour l\'équilibre.', 'Sensation d\'étirement à l\'avant de la cuisse.'],
    commonMistakes: ['Se pencher en avant', 'Genou qui sort vers le côté'],
    defaultSets: 2,
    defaultDuration: 30,
    defaultRest: 15,
  },
  {
    id: 'hamstring_stretch',
    name: 'Étirement Ischio-Jambiers',
    category: 'stretching',
    muscleGroups: ['hamstrings'],
    primaryMuscle: 'hamstrings',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Étirement des ischio-jambiers assis ou debout.',
    instructions: [
      'Assis, une jambe tendue, l\'autre fléchie.',
      'Penche-toi vers la jambe tendue en gardant le dos droit.',
    ],
    coachTips: ['Cherche l\'étirement derrière la cuisse, pas la douleur dans le genou.'],
    commonMistakes: ['Arrondir le dos', 'Fléchir le genou de la jambe étirée'],
    defaultSets: 2,
    defaultDuration: 30,
    defaultRest: 15,
  },
  {
    id: 'hip_flexor_stretch',
    name: 'Étirement Fléchisseurs de Hanche',
    category: 'stretching',
    muscleGroups: ['quads', 'glutes'],
    primaryMuscle: 'glutes',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Étirement essentiel pour contrebalancer la position assise.',
    instructions: [
      'Fente basse, genou arrière au sol.',
      'Avance légèrement les hanches.',
      'Maintiens le buste droit.',
    ],
    coachTips: ['Contracte légèrement le fessier du côté étiré.'],
    commonMistakes: ['Se pencher trop en avant', 'Genou avant qui dépasse les orteils'],
    defaultSets: 2,
    defaultDuration: 30,
    defaultRest: 15,
  },
  {
    id: 'chest_stretch',
    name: 'Étirement Pectoraux',
    category: 'stretching',
    muscleGroups: ['chest', 'shoulders'],
    primaryMuscle: 'chest',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Étirement des pectoraux et de l\'avant des épaules.',
    instructions: [
      'Mains croisées dans le dos ou contre un mur.',
      'Ouvre la poitrine vers l\'avant.',
    ],
    coachTips: ['Excellent après une séance pectoraux ou une journée devant l\'ordinateur.'],
    commonMistakes: ['Cambrer excessivement le dos'],
    defaultSets: 2,
    defaultDuration: 30,
    defaultRest: 15,
  },
  {
    id: 'spine_rotation',
    name: 'Rotation de la Colonne',
    category: 'stretching',
    muscleGroups: ['lower_back', 'abs'],
    primaryMuscle: 'lower_back',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Mobilisation et étirement de la colonne vertébrale.',
    instructions: [
      'Allongé sur le dos, genou plié d\'un côté.',
      'Laisse le genou tomber de l\'autre côté.',
      'Bras en croix, regarde vers le côté opposé.',
    ],
    coachTips: ['Respire profondément pour aller plus loin dans l\'étirement.'],
    commonMistakes: ['Lever les épaules du sol'],
    defaultSets: 2,
    defaultDuration: 30,
    defaultRest: 15,
  },
  {
    id: 'cat_cow',
    name: 'Chat / Vache',
    category: 'stretching',
    muscleGroups: ['lower_back', 'abs'],
    primaryMuscle: 'lower_back',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Mobilisation dynamique de la colonne, excellent pour s\'échauffer et récupérer.',
    instructions: [
      'À quatre pattes.',
      'Chat : arrondir le dos vers le haut.',
      'Vache : descendre le ventre et lever la tête.',
      'Alterner lentement.',
    ],
    coachTips: ['Synchronise avec la respiration.'],
    commonMistakes: ['Mouvements trop rapides'],
    defaultSets: 2,
    defaultReps: 10,
    defaultRest: 15,
  },
  {
    id: 'pigeon_pose',
    name: 'Posture du Pigeon',
    category: 'stretching',
    muscleGroups: ['glutes', 'hamstrings', 'quads'],
    primaryMuscle: 'glutes',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Étirement profond des fessiers et des hanches.',
    instructions: [
      'À partir d\'une position à quatre pattes, glisse un genou vers l\'avant.',
      'La jambe arrière tendue, hanches au sol.',
      'Penche-toi en avant pour approfondir.',
    ],
    coachTips: ['Un des meilleurs étirements fessiers. À faire après chaque séance jambes.'],
    commonMistakes: ['Hanches pas carrées', 'Forcer trop vite'],
    defaultSets: 2,
    defaultDuration: 45,
    defaultRest: 15,
  },
  {
    id: 'shoulder_cross_stretch',
    name: 'Étirement Épaule Croisée',
    category: 'stretching',
    muscleGroups: ['shoulders', 'back'],
    primaryMuscle: 'shoulders',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Étirement des épaules et du deltoïde postérieur.',
    instructions: [
      'Amène un bras tendu devant toi.',
      'L\'autre bras le maintient contre la poitrine.',
    ],
    coachTips: ['Garde les épaules basses pendant l\'étirement.'],
    commonMistakes: ['Épaule qui monte'],
    defaultSets: 2,
    defaultDuration: 30,
    defaultRest: 15,
  },
  {
    id: 'calf_stretch',
    name: 'Étirement Mollets',
    category: 'stretching',
    muscleGroups: ['calves'],
    primaryMuscle: 'calves',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Étirement du soléaire et du gastrocnémien.',
    instructions: [
      'Face à un mur, une jambe en avant fléchie, l\'autre tendue derrière.',
      'Talon arrière bien à plat.',
      'Penche-toi vers le mur.',
    ],
    coachTips: ['Pour le soléaire : fléchis légèrement le genou arrière.'],
    commonMistakes: ['Lever le talon', 'Ne pas sentir l\'étirement'],
    defaultSets: 2,
    defaultDuration: 30,
    defaultRest: 15,
  },
  {
    id: 'childs_pose',
    name: 'Posture de l\'Enfant',
    category: 'stretching',
    muscleGroups: ['lower_back', 'shoulders', 'glutes'],
    primaryMuscle: 'lower_back',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Posture de relaxation et d\'étirement du dos, des épaules et des hanches.',
    instructions: [
      'À genoux, assis sur les talons.',
      'Penche-toi en avant, bras tendus devant.',
      'Front vers le sol.',
    ],
    coachTips: ['Excellent pour décompresser le dos après le soulevé de terre.'],
    commonMistakes: ['Fessiers qui se lèvent'],
    defaultSets: 2,
    defaultDuration: 45,
    defaultRest: 15,
  },
  {
    id: 'neck_stretch',
    name: 'Étirement Nuque',
    category: 'stretching',
    muscleGroups: ['back', 'shoulders'],
    primaryMuscle: 'back',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Étirement doux de la nuque et des trapèzes.',
    instructions: [
      'Incline doucement la tête sur le côté.',
      'Main du même côté tire légèrement.',
      'Autre main au sol pour l\'étirement.',
    ],
    coachTips: ['Très doux. Jamais de pression brutale sur la nuque.'],
    commonMistakes: ['Trop forcer'],
    defaultSets: 2,
    defaultDuration: 20,
    defaultRest: 10,
  },
  {
    id: 'world_greatest_stretch',
    name: 'Le Plus Grand Étirement du Monde',
    category: 'stretching',
    muscleGroups: ['full_body', 'glutes', 'hamstrings', 'quads', 'chest'],
    primaryMuscle: 'full_body',
    equipment: ['none'],
    difficulty: 'intermediate',
    description: 'Étirement complet en une seule position, excellent avant l\'entraînement.',
    instructions: [
      'Fente avant profonde.',
      'Main intérieure au sol à côté du pied avant.',
      'Rotation vers l\'autre main vers le plafond.',
      'Garde le talon arrière levé.',
    ],
    coachTips: ['Fait partie de tout bon échauffement dynamique.'],
    commonMistakes: ['Mouvement trop rapide', 'Perdre l\'équilibre'],
    defaultSets: 2,
    defaultReps: 8,
    defaultRest: 30,
  },
  {
    id: 'foam_roll_quads',
    name: 'Rouleau Mousse Quadriceps',
    category: 'stretching',
    muscleGroups: ['quads'],
    primaryMuscle: 'quads',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Auto-massage avec un foam roller pour relâcher les quadriceps.',
    instructions: [
      'Face au sol, rouleau sous les cuisses.',
      'Roule lentement d\'un genou vers l\'aine.',
      'Pause sur les zones sensibles.',
    ],
    coachTips: ['Respire profondément sur les zones douloureuses.'],
    commonMistakes: ['Aller trop vite', 'Rouler sur les zones trop douloureuses'],
    defaultSets: 2,
    defaultDuration: 60,
    defaultRest: 15,
  },
  {
    id: 'thoracic_extension',
    name: 'Extension Thoracique',
    category: 'stretching',
    muscleGroups: ['back', 'chest'],
    primaryMuscle: 'back',
    equipment: ['none'],
    difficulty: 'beginner',
    description: 'Mobilité thoracique, contre la cyphose et les tensions du haut du dos.',
    instructions: [
      'Assis, mains derrière la tête.',
      'Penche-toi en arrière sur le dossier d\'une chaise ou un foam roller.',
    ],
    coachTips: ['Essayer de fléchir le thorax et non le lombaire.'],
    commonMistakes: ['S\'étirer sur les lombaires'],
    defaultSets: 2,
    defaultReps: 10,
    defaultRest: 15,
  },
];

// ─── Workout Templates ────────────────────────────────────────────────────────

const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: 'full_body_beginner',
    name: 'Full Body Débutant',
    description: 'Séance complète pour débutants, 3x par semaine',
    category: 'strength',
    type: 'strength',
    bodyTarget: 'full_body',
    difficulty: 'beginner',
    estimatedDuration: 45,
    equipment: ['barbell', 'dumbbells', 'bench'],
    createdAt: new Date().toISOString(),
    isCustom: false,
    exercises: [
      { exerciseId: 'squat', sets: 3, reps: 10, rest: 120, order: 1 },
      { exerciseId: 'bench_press', sets: 3, reps: 10, rest: 90, order: 2 },
      { exerciseId: 'barbell_row', sets: 3, reps: 10, rest: 90, order: 3 },
      { exerciseId: 'overhead_press', sets: 3, reps: 10, rest: 75, order: 4 },
      { exerciseId: 'romanian_deadlift', sets: 3, reps: 12, rest: 90, order: 5 },
      { exerciseId: 'plank', sets: 3, duration: 30, rest: 45, order: 6 },
    ],
  },
  {
    id: 'ppl_push',
    name: 'PPL - Push (Poussée)',
    description: 'Jour poussée du programme Push Pull Legs',
    category: 'strength',
    type: 'strength',
    bodyTarget: 'upper_body',
    difficulty: 'intermediate',
    estimatedDuration: 60,
    equipment: ['barbell', 'dumbbells', 'cable', 'bench'],
    createdAt: new Date().toISOString(),
    isCustom: false,
    exercises: [
      { exerciseId: 'bench_press', sets: 4, reps: 8, rest: 120, order: 1 },
      { exerciseId: 'incline_bench_press', sets: 3, reps: 10, rest: 90, order: 2 },
      { exerciseId: 'overhead_press', sets: 4, reps: 8, rest: 90, order: 3 },
      { exerciseId: 'lateral_raise', sets: 3, reps: 15, rest: 60, order: 4 },
      { exerciseId: 'tricep_dip', sets: 3, reps: 10, rest: 75, order: 5 },
      { exerciseId: 'skull_crusher', sets: 3, reps: 12, rest: 60, order: 6 },
      { exerciseId: 'cable_crossover', sets: 3, reps: 15, rest: 60, order: 7 },
    ],
  },
  {
    id: 'ppl_pull',
    name: 'PPL - Pull (Tirage)',
    description: 'Jour tirage du programme Push Pull Legs',
    category: 'strength',
    type: 'strength',
    bodyTarget: 'upper_body',
    difficulty: 'intermediate',
    estimatedDuration: 60,
    equipment: ['barbell', 'cable', 'pull_up_bar'],
    createdAt: new Date().toISOString(),
    isCustom: false,
    exercises: [
      { exerciseId: 'deadlift', sets: 4, reps: 5, rest: 180, order: 1 },
      { exerciseId: 'pull_up', sets: 4, reps: 8, rest: 90, order: 2 },
      { exerciseId: 'barbell_row', sets: 4, reps: 8, rest: 90, order: 3 },
      { exerciseId: 'lat_pulldown', sets: 3, reps: 10, rest: 75, order: 4 },
      { exerciseId: 'seated_cable_row', sets: 3, reps: 12, rest: 75, order: 5 },
      { exerciseId: 'barbell_curl', sets: 3, reps: 12, rest: 60, order: 6 },
      { exerciseId: 'face_pull', sets: 3, reps: 15, rest: 60, order: 7 },
    ],
  },
  {
    id: 'ppl_legs',
    name: 'PPL - Legs (Jambes)',
    description: 'Jour jambes du programme Push Pull Legs',
    category: 'strength',
    type: 'strength',
    bodyTarget: 'lower_body',
    difficulty: 'intermediate',
    estimatedDuration: 60,
    equipment: ['barbell', 'machine', 'bench'],
    createdAt: new Date().toISOString(),
    isCustom: false,
    exercises: [
      { exerciseId: 'squat', sets: 5, reps: 5, rest: 180, order: 1 },
      { exerciseId: 'romanian_deadlift', sets: 4, reps: 8, rest: 120, order: 2 },
      { exerciseId: 'leg_press', sets: 3, reps: 12, rest: 90, order: 3 },
      { exerciseId: 'lunge', sets: 3, reps: 12, rest: 75, order: 4 },
      { exerciseId: 'seated_leg_curl', sets: 3, reps: 12, rest: 60, order: 5 },
      { exerciseId: 'calf_raise', sets: 4, reps: 15, rest: 45, order: 6 },
    ],
  },
  {
    id: 'football_prep',
    name: 'Préparation Physique Football',
    description: 'Séance spécifique prépa physique football',
    category: 'football',
    type: 'sport_specific',
    bodyTarget: 'full_body',
    difficulty: 'intermediate',
    estimatedDuration: 60,
    equipment: ['none'],
    createdAt: new Date().toISOString(),
    isCustom: false,
    exercises: [
      { exerciseId: 'sprint_10m', sets: 6, duration: 5, rest: 90, order: 1 },
      { exerciseId: 'agility_ladder', sets: 4, duration: 20, rest: 60, order: 2 },
      { exerciseId: 'cone_slalom', sets: 5, duration: 15, rest: 45, order: 3 },
      { exerciseId: 'box_jump', sets: 4, reps: 8, rest: 90, order: 4 },
      { exerciseId: 'lateral_sprint', sets: 5, duration: 20, rest: 45, order: 5 },
      { exerciseId: 'interval_run_football', sets: 5, duration: 240, rest: 60, order: 6 },
    ],
  },
  {
    id: 'rugby_prep',
    name: 'Préparation Physique Rugby',
    description: 'Séance force et explosivité pour le rugby',
    category: 'rugby',
    type: 'sport_specific',
    bodyTarget: 'full_body',
    difficulty: 'advanced',
    estimatedDuration: 75,
    equipment: ['barbell', 'none'],
    createdAt: new Date().toISOString(),
    isCustom: false,
    exercises: [
      { exerciseId: 'power_clean', sets: 4, reps: 4, rest: 180, order: 1 },
      { exerciseId: 'squat', sets: 4, reps: 5, rest: 180, order: 2 },
      { exerciseId: 'deadlift', sets: 3, reps: 5, rest: 180, order: 3 },
      { exerciseId: 'rugby_sprint', sets: 6, duration: 8, rest: 120, order: 4 },
      { exerciseId: 'bounding', sets: 4, reps: 8, rest: 90, order: 5 },
      { exerciseId: 'sled_push', sets: 5, duration: 20, rest: 120, order: 6 },
      { exerciseId: 'neck_strengthening', sets: 3, reps: 15, rest: 30, order: 7 },
    ],
  },
  {
    id: 'cardio_fat_loss',
    name: 'Cardio Perte de Poids',
    description: 'Séance cardio pour maximiser la dépense calorique',
    category: 'cardio',
    type: 'cardio',
    bodyTarget: 'full_body',
    difficulty: 'intermediate',
    estimatedDuration: 45,
    equipment: ['bodyweight'],
    createdAt: new Date().toISOString(),
    isCustom: false,
    exercises: [
      { exerciseId: 'jump_rope', sets: 5, duration: 60, rest: 30, order: 1 },
      { exerciseId: 'hiit_sprint', sets: 8, duration: 30, rest: 30, order: 2 },
      { exerciseId: 'burpee', sets: 3, reps: 10, rest: 60, order: 3 },
      { exerciseId: 'mountain_climber', sets: 3, duration: 30, rest: 30, order: 4 },
      { exerciseId: 'tabata', sets: 8, duration: 20, rest: 10, order: 5 },
    ],
  },
  {
    id: 'recovery_stretching',
    name: 'Récupération & Étirements',
    description: 'Séance de récupération active et étirements complets',
    category: 'stretching',
    type: 'recovery',
    bodyTarget: 'full_body',
    difficulty: 'beginner',
    estimatedDuration: 30,
    equipment: ['none'],
    createdAt: new Date().toISOString(),
    isCustom: false,
    exercises: [
      { exerciseId: 'cat_cow', sets: 2, reps: 10, rest: 15, order: 1 },
      { exerciseId: 'quad_stretch', sets: 2, duration: 30, rest: 15, order: 2 },
      { exerciseId: 'hamstring_stretch', sets: 2, duration: 30, rest: 15, order: 3 },
      { exerciseId: 'hip_flexor_stretch', sets: 2, duration: 30, rest: 15, order: 4 },
      { exerciseId: 'pigeon_pose', sets: 2, duration: 45, rest: 15, order: 5 },
      { exerciseId: 'chest_stretch', sets: 2, duration: 30, rest: 15, order: 6 },
      { exerciseId: 'spine_rotation', sets: 2, duration: 30, rest: 15, order: 7 },
      { exerciseId: 'childs_pose', sets: 2, duration: 45, rest: 15, order: 8 },
    ],
  },
];

// ─── Programs ─────────────────────────────────────────────────────────────────

const PROGRAMS: Program[] = [
  {
    id: 'prog_fullbody_beginner',
    name: 'Full Body Débutant 8 Semaines',
    description: 'Programme idéal pour débuter la musculation. 3 séances par semaine, chaque muscle travaillé à chaque séance.',
    category: 'strength',
    objective: 'Apprentissage des fondamentaux et premiers gains',
    difficulty: 'beginner',
    durationWeeks: 8,
    sessionsPerWeek: 3,
    equipment: ['barbell', 'dumbbells', 'bench'],
    isCustom: false,
    createdAt: new Date().toISOString(),
    weeks: Array.from({ length: 8 }, (_, i) => ({
      weekNumber: i + 1,
      workouts: [
        { dayOfWeek: 0, workoutTemplateId: 'full_body_beginner' },
        { dayOfWeek: 2, workoutTemplateId: 'full_body_beginner' },
        { dayOfWeek: 4, workoutTemplateId: 'full_body_beginner' },
      ],
    })),
  },
  {
    id: 'prog_ppl',
    name: 'PPL Intermédiaire 12 Semaines',
    description: 'Push Pull Legs - programme classique pour intermédiaires. 6 jours par semaine avec un jour de repos.',
    category: 'strength',
    objective: 'Hypertrophie et force',
    difficulty: 'intermediate',
    durationWeeks: 12,
    sessionsPerWeek: 6,
    equipment: ['barbell', 'dumbbells', 'cable', 'bench', 'pull_up_bar', 'machine'],
    isCustom: false,
    createdAt: new Date().toISOString(),
    weeks: Array.from({ length: 12 }, (_, i) => ({
      weekNumber: i + 1,
      workouts: [
        { dayOfWeek: 0, workoutTemplateId: 'ppl_push' },
        { dayOfWeek: 1, workoutTemplateId: 'ppl_pull' },
        { dayOfWeek: 2, workoutTemplateId: 'ppl_legs' },
        { dayOfWeek: 4, workoutTemplateId: 'ppl_push' },
        { dayOfWeek: 5, workoutTemplateId: 'ppl_pull' },
        { dayOfWeek: 6, workoutTemplateId: 'ppl_legs' },
      ],
    })),
  },
  {
    id: 'prog_football',
    name: 'Préparation Physique Football 6 Semaines',
    description: 'Programme de pré-saison pour footballeurs. Améliore vitesse, explosivité et endurance spécifique.',
    category: 'football',
    objective: 'Performance footballistique',
    difficulty: 'intermediate',
    durationWeeks: 6,
    sessionsPerWeek: 4,
    equipment: ['none'],
    isCustom: false,
    createdAt: new Date().toISOString(),
    weeks: Array.from({ length: 6 }, (_, i) => ({
      weekNumber: i + 1,
      workouts: [
        { dayOfWeek: 0, workoutTemplateId: 'football_prep' },
        { dayOfWeek: 1, workoutTemplateId: 'full_body_beginner' },
        { dayOfWeek: 3, workoutTemplateId: 'football_prep' },
        { dayOfWeek: 5, workoutTemplateId: 'cardio_fat_loss' },
      ],
    })),
  },
  {
    id: 'prog_rugby',
    name: 'Préparation Physique Rugby 8 Semaines',
    description: 'Programme pour joueurs de rugby. Force, explosivité et spécificités du rugby.',
    category: 'rugby',
    objective: 'Performance rugby',
    difficulty: 'advanced',
    durationWeeks: 8,
    sessionsPerWeek: 4,
    equipment: ['barbell', 'none'],
    isCustom: false,
    createdAt: new Date().toISOString(),
    weeks: Array.from({ length: 8 }, (_, i) => ({
      weekNumber: i + 1,
      workouts: [
        { dayOfWeek: 0, workoutTemplateId: 'rugby_prep' },
        { dayOfWeek: 1, workoutTemplateId: 'ppl_legs' },
        { dayOfWeek: 3, workoutTemplateId: 'rugby_prep' },
        { dayOfWeek: 5, workoutTemplateId: 'ppl_pull' },
      ],
    })),
  },
  {
    id: 'prog_fat_loss',
    name: 'Perte de Poids 8 Semaines',
    description: 'Combinaison cardio et renforcement musculaire pour maximiser la perte de masse grasse.',
    category: 'cardio',
    objective: 'Perte de poids et tonification',
    difficulty: 'intermediate',
    durationWeeks: 8,
    sessionsPerWeek: 5,
    equipment: ['bodyweight', 'dumbbells'],
    isCustom: false,
    createdAt: new Date().toISOString(),
    weeks: Array.from({ length: 8 }, (_, i) => ({
      weekNumber: i + 1,
      workouts: [
        { dayOfWeek: 0, workoutTemplateId: 'full_body_beginner' },
        { dayOfWeek: 1, workoutTemplateId: 'cardio_fat_loss' },
        { dayOfWeek: 2, workoutTemplateId: 'full_body_beginner' },
        { dayOfWeek: 4, workoutTemplateId: 'cardio_fat_loss' },
        { dayOfWeek: 5, workoutTemplateId: 'full_body_beginner' },
      ],
    })),
  },
];

// ─── Seed Function ────────────────────────────────────────────────────────────

export async function seedDatabase(db: SQLite.SQLiteDatabase): Promise<void> {
  const result = await db.getFirstAsync<{ count: number }>(
    'SELECT COUNT(*) as count FROM exercises'
  );

  if (result && result.count > 0) return;

  for (const exercise of EXERCISES) {
    await db.runAsync(
      `INSERT OR IGNORE INTO exercises
        (id, name, category, muscle_groups, primary_muscle, equipment, difficulty,
         description, instructions, coach_tips, common_mistakes, image_url, video_url,
         default_sets, default_reps, default_duration, default_rest)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        exercise.id,
        exercise.name,
        exercise.category,
        JSON.stringify(exercise.muscleGroups),
        exercise.primaryMuscle,
        JSON.stringify(exercise.equipment),
        exercise.difficulty,
        exercise.description,
        JSON.stringify(exercise.instructions),
        JSON.stringify(exercise.coachTips),
        JSON.stringify(exercise.commonMistakes),
        exercise.imageUrl ?? null,
        exercise.videoUrl ?? null,
        exercise.defaultSets ?? 3,
        exercise.defaultReps ?? null,
        exercise.defaultDuration ?? null,
        exercise.defaultRest ?? 60,
      ]
    );
  }

  for (const template of WORKOUT_TEMPLATES) {
    await db.runAsync(
      `INSERT OR IGNORE INTO workout_templates
        (id, name, description, category, type, body_target, difficulty,
         estimated_duration, exercises, equipment, created_at, is_custom, program_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        template.id,
        template.name,
        template.description ?? null,
        template.category,
        template.type,
        template.bodyTarget,
        template.difficulty,
        template.estimatedDuration,
        JSON.stringify(template.exercises),
        JSON.stringify(template.equipment),
        template.createdAt,
        template.isCustom ? 1 : 0,
        template.programId ?? null,
      ]
    );
  }

  for (const program of PROGRAMS) {
    await db.runAsync(
      `INSERT OR IGNORE INTO programs
        (id, name, description, category, objective, difficulty, duration_weeks,
         sessions_per_week, weeks, equipment, image_url, is_custom, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        program.id,
        program.name,
        program.description,
        program.category,
        program.objective,
        program.difficulty,
        program.durationWeeks,
        program.sessionsPerWeek,
        JSON.stringify(program.weeks),
        JSON.stringify(program.equipment),
        program.imageUrl ?? null,
        program.isCustom ? 1 : 0,
        program.createdAt,
      ]
    );
  }

  const now = new Date().toISOString();
  await db.runAsync(
    `INSERT OR IGNORE INTO user_profile (id, name, level, sports, preferred_equipment, onboarding_completed, created_at)
     VALUES ('default', 'Athlete', 'beginner', '[]', '[]', 0, ?)`,
    [now]
  );
}
